### ISSUE TITLE
안녕하세요! 코멘트 전달드립니다!

### ISSUE THREAD

**Issue by yun-melody** [WON-JIN-LEE/nodejs-dev-01#1]
안녕하세요 원진님!
과제 하시느라 정말 수고 많으셨습니다.
API Document를 따로 작성해주신 부분이 정말 좋은 것 같아요!🌱
그리고 **git commit 메세지**와 **env**로 보안적인 부분을 신경쓰신 부분이 좋았습니다.🤭
그럼 과제 코멘트 전달드립니다!

**1. 예외처리**
게시글 상세 조회 API를 예로 들어서 말씀드리자면,
해당 postId가 원진님이 원하시는 '1'와 같은 형식대로 들어오지 않고 만약 'abc'와 같은 문자로 들어온다면 Number로 형변환 하는 과정에서 NaN으로 바뀌게 됩니다. 이 경우에는 현재 상태로는 예외 처리가 되어 있지 않아서 무한로딩이 걸리게 되는데, 이런 부분을 신경써주신다면 더 좋을 꺼 같아요!
게시글 작성에서도 이름이 게시글 schema에서 필수값이나, API 로직상으로는 예외처리 하는 부분이 없어서 여기도 추가해주시면 좋을 것 같습니다!
```javascript
// 게시글 상세 조회 API
router.get("/posts/:postId", async (req, res) => {
    const {postId} = req.params;
    const [detail] = await Posts.find({post_id: Number(postId)});

    res.json({detail});
});

```

**2. findOne**
게시글 상세 조회와 같이 한 개의 값을 찾아올때는 findOne을 이용해보시면 좋을 것 같습니다!

끝으로, 전체적으로 잘 작성해주셔서 예외처리 하는 부분만 좀 더 신경쓰시면 
더 좋은 코드가 될 것 같습니다!

**Comment by WON-JIN-LEE** [comment]
코멘트 확인했습니다. 지윤님 
예외처리 부분 수정해보겠습니다.

**Comment by WON-JIN-LEE** [comment]
1.erro처리
에러 처리 부분은 수정하였습니다.

2. findOne
findOne을 이용해 게시글 상세 조회 되도록 수정하였습니다.

코멘트 감사합니다.
