### ISSUE TITLE
안녕하세요! 과제 코멘트 남겨드리고 갑니다!!!

### ISSUE THREAD

**Issue by player31-kks** [WON-JIN-LEE/nodejs-dev-01#2]
안녕하세요 원진님 기술매니저 금교석입니다.
우선 과제 정말 잘하셨고 수고하셨습니다. 그럼 제가 몇 가지 코멘트 작성해드릴게요

### 1. error 처리
```javascript
  if (name === "" || title === "" || content === "") 
```
이 부분에 대한 에러 처리를 할 경우 undefined와 null에 관에서는 처리할 수 없습니다. 그래서 
``` javascript
if(!name || !title || !content)
```
로 바꾸면 더 깔끔한 에러 처리를 할 수 있을 것 같습니다.

### 2. ID값
* 스키마를 설계하실 때 id는 해당 스키마의 고유한 정보이기 때문에 고유의 번호를 사용 해야 합니다. 그래서 고유 아이디는 mongoose에서 제공하는 ObjectId를 사용하는 것이 좋습니다. 만약 관계형 DB를 사용할 경우는 UUID로 사용하는 것이 좋습니다.!!
이 글을 참고 해보시면 좋을 것 같아요  https://wjdtn7823.tistory.com/59

전반적으로 코드를 깔끔하게 쓰셔서 코드 리뷰하는데 너무 편했습니다. API 명세도 깔끔하게 적으셔서 앞으로 프론트와 작업 하실 때도 이렇게 진행하면 좋을 것 같습니다. 과제 수고하셨고 L2~L5도 화이팅입니다!!!😀😀😀

**Comment by WON-JIN-LEE** [comment]
1. erro처리
에러 처리 부분은 수정하였습니다.

2. ID 값
시간이 충분할 때 오브젝트 id로 수정해보겠습니다.
다음 프로젝트에서는 mongoose에서 제공하는  ObjectId를 사용할 수 있도록 하겠습니다.

코멘트 감사합니다.
